# Site settings
title: LCC Cirebon
description: >
  LP3I Computer Club Cirebon. Belajar, berbagi, bertakwa.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lcc.cirebob.lp3i.ac.id" # the base hostname & protocol for your site
twitter_username: lcc_crb
github_username:  lcc-cirebon

# Build settings
markdown: kramdown
